In [3]:
##############2.3.1 创建数组#############


import numpy as np
vector = np.array([1,2,3,4])  #直接导入向量

martrix = np.array([[1,'Tim'],[2,'Joey'],[3,'Johnny'],[4,'Frank']])  #导入矩阵

print(vector)
print(martrix)

[1 2 3 4]
[['1' 'Tim']
 ['2' 'Joey']
 ['3' 'Johnny']
 ['4' 'Frank']]


In [17]:
#############2.3.2 创建Numpy数组###############


a = np.zeros(10)
print(a)
a.dtype

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


dtype('float64')

In [12]:
np.zeros(10,dtype = int) #强制规定类型

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros(shape = (3,4)) #多维矩阵

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4)) #全1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.full((3,5),121)  #full设置一个默认值为121的3*4的矩阵

array([[121, 121, 121, 121, 121],
       [121, 121, 121, 121, 121],
       [121, 121, 121, 121, 121]])

In [16]:
np.arange(0,20,2)  #arange接受三个参数，范围是前闭后开，及[0,20)的数，间距步长为2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.linspace(0,10,5)  #linspace（前闭后闭）用于对Numpy矩阵进行等分，例将0-10等分成5份

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
###Numpy生成随机数矩阵
np.random.randint(0,10,5)    #生成范围0-9(前闭后开)，个数5个

array([3, 9, 8, 6, 2])

In [23]:
np.random.randint(4,9,(3,5))   #生成多维矩阵 三行五列 数值介于4-8之间

array([[7, 8, 4, 5, 7],
       [4, 4, 5, 8, 8],
       [5, 6, 8, 6, 8]])

In [26]:
np.random.random(10)    #随机生成0-1之间的浮点数，向量长度为10

array([0.98886109, 0.74816565, 0.28044399, 0.78927933, 0.10322601,
       0.44789353, 0.9085955 , 0.29361415, 0.28777534, 0.13002857])

In [27]:
np.random.random((2,4))     #随机生成0-1之间的浮点数  形成两行四列的矩阵

array([[0.01936696, 0.67883553, 0.21162812, 0.26554666],
       [0.49157316, 0.05336255, 0.57411761, 0.14672857]])

In [29]:
np.random.normal(loc = 0,scale = 1,size = (3,4))  #正态分布 loc(float)均值  ，scale（float）标准差，size（int或者整数元组） 默认为none

array([[ 1.65980218,  0.74204416, -0.19183555, -0.88762896],
       [-0.74715829,  1.6924546 ,  0.05080775, -0.63699565],
       [ 0.19091548,  2.10025514,  0.12015895,  0.61720311]])

In [10]:
################2.3.3 获取Numpy属性##########################
import numpy as np
a = np.arange(15)  
b= np.arange(15).reshape(3,5)   #reshape改变矩阵的行列数
c = b.reshape(5,3)
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [12]:
print(a.shape)    #shape显示矩阵的行列数
print(b.shape)
print(c.shape)

(15,)
(3, 5)
(5, 3)


In [15]:
print(a.ndim)   #ndim显示矩阵的维度
print(b.ndim) 
print(c.ndim) 

1
2
2


In [25]:
a.reshape(5,-1)  #只设置需要的行数5，列数由计算机自己计算

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
b.reshape(-1,5)  #只设置需要的列数3，行数由计算机自己计算

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
##################### 2.3.4  Numpy数组索引#######################
matrix = np.array([[1,2,3],[20,30,40]])
print(matrix[0,1])    #定位操作

2


In [28]:
#################### 2.3.5  切片#############################

matrix = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
print(matrix[:,1])      #所有行且列索引为1
print(matrix[:,0:2])      #所有行且列索引为0和1
print(matrix[1:3,:])        #所有列且行索引为1和2
print(matrix[1:3,0:2])      #行索引为1-2，列索引为0-1


[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]
[[20 25 30]
 [35 40 45]]
[[20 25]
 [35 40]]


In [31]:
################## 2.3.6Numpy中的矩阵运算#########################
myones = np.ones([3,3])
myeye = np.eye(3)   #单位矩阵
print(myeye)
print(myones - myeye)   #直接减法计算

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [34]:
#预置函数
np.sin(a)
np.cos(a)
np.tan(a)
np.sqrt(a)
np.abs(a)     #取绝对值


In [36]:
#矩阵之间的点乘
mymatrix = np.array([[1,2,3],[4,5,6]])
a = np.array([[1,2],[3,4],[5,6]])
print(mymatrix.shape[1] == a.shape[0])
print(mymatrix.dot(a))

True
[[22 28]
 [49 64]]


In [37]:
#矩阵的转置
a = np.array([[1,2,3],[4,5,6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [2]:
#矩阵的逆
import numpy as np
import numpy.linalg as lg
A =np.array([[0,1],[2,3]])
invA = lg.inv(A)
print(invA)
print(A.dot(invA))

[[-1.5  0.5]
 [ 1.   0. ]]
[[1. 0.]
 [0. 1.]]


In [6]:
################ 2.3.7 数据类型转换 ######################
vector = np.array(["1","2","3"])
print(vector)
vector = vector.astype(float)  #astype调用返回一个新的数组即原数组的备份
print(vector)

['1' '2' '3']
[1. 2. 3.]


In [7]:
################  2.3.8  Numpy的统计计算方法##################
#内置方法
sum()
mean()  #平均值
max()
median()  #中位数

In [8]:
vector = np.array([5,10,15,20])
vector.sum()

50

In [14]:
matrix = np.array([[5,10,15],[20,10,30],[35,40,45]])
  
print(matrix.sum(axis =1)) #计算每行的和

print(matrix.sum())

[ 30  60 120]
210


In [20]:
##################### Numpy中的arg运算############################\
print(np.argmax([1,2,6,3,2]))   #argmax返回最大的数所对应的索引（位置）
print(np.argmin([1,2,6,3,2]))   #argmin返回最小的数所对应的索引（位置）

2
0


In [21]:
#Numpy矩阵排序和索引
x = np.arange(15)
print(x)
np.random.shuffle(x)  #随机打乱
print(x)
sx = np.argsort(x)    #从小到大排序，返回索引值
print(sx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  0  7  9  8  5 12 10  1  4  2 13 14 11  6]
[ 1  8 10  0  9  5 14  2  4  3  7 13  6 11 12]


In [23]:
###################### 2.3.10  FancyIndexing ########################
#返回索引向量中的多个值。如返回第三个，第五个以及第八个元素
x = np.arange(15)
ind = [3,5,8]
print(x[ind])

[3 5 8]


In [24]:
#从一维向量宗构建新的二维矩阵
x = np.arange(15)
np.random.shuffle(x)
ind = np.array([[2,1],[1,3]])   #新建的二维矩阵的第一行是x中索引值为0和2的值，第二行是x中索引为1和3的值
print(x)
print(x[ind])

[ 4  9  7 11 12  8  0 14  6 10  5  1  3  2 13]
[[ 7  9]
 [ 9 11]]


In [25]:
##################### 2.3.11 Numpy数组比较 ############################
matrix = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
m = (matrix ==25)
n = (matrix >30)
print(m)
print(n)

[[False False False]
 [False  True False]
 [False False False]]
[[False False False]
 [False False False]
 [ True  True  True]]
